# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 696d146d47b406c11b3584f43bc55f8774e034fe2063305b11a72098afbb5f08308c9627f2507c63af2bc9a8a3ea7536ec509689099e7491594ef9dc4c1922e0

test:
  secret_key_base: e1fba9e834a89aa508a3f7c9b93299b1a2cb8901f138b3550ee752dacab75324b6c157a4a8a234139e8b397e6baadef5e391cc7592c221c9157ad6c7dfc61b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
